root = "."
tmp_dir = "temp"

[build]
  cmd = "go build -o ./temp/main cmd/main.go"
  bin = "./temp/main"
  full_bin = "./temp/main"
  include_ext = ["go", "templ", "view"]
  exclude_dir = ["assets", "vendor"]
  kill_delay = "5s"
  log = "build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true
  color = true

[misc]
  clean_on_exit = true

[watch]
  include_ext = ["go", "templ"]
  exclude_dir = ["assets", "internal/database", "web/templ", "vendor"]


[screen]
  clear_on_rebuild = false
  keep_scroll = true
