services:
 
  postgres:
    image: postgres
    container_name: pg-container
    environment:
      - POSTGRES_PASSWORD=123  # Set the PostgreSQL password
      - POSTGRES_DB=mydatabase  # Optional: Set the name of the database to create initially
      - POSTGRES_HOST_AUTH_METHOD=trust  # Add this line
      # Add these lines to allow connections
      - POSTGRES_INITDB_ARGS=--auth-host=trust
      - POSTGRES_INITDB_ARGS=--auth-local=trust
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data  # Persist data in the volume "pg-data"
    restart: always

  pgAdmin4:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com # Set the PostgreSQL password
      - PGADMIN_DEFAULT_PASSWORD=123  # Set the PostgreSQL password
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always

volumes:
  pg-data:  # Define a named volume called "pg-data"
  pgadmin-data:
